name: main

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup environment
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false
          poetry install
      - name: Linters
        run: |
          black --check .
          isort --check .
          flake8 .
      - name: Pytest
        run: |
          pytest
