name: release

on:
  push:
    tags:
      - '[12].[0-9]+.[0-9]+'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false
          poetry install
      - name: Build package
        run: poetry build
      - name: Publish package
        run: poetry publish -u __token__ -p ${{ secrets.PYPI_TOKEN }}
